config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
  
=begin
  acciones CRUD(create,read,updated,delete)
    get '/articles' index
    post '/articles'  create
    delete '/articles'  delete
    get 'articles/:id'  show
    get 'articles/new'  new
    get 'articles/:id/edit' edit
    patch '/articles/:id' update
    put '/articles/:id' update
=end

end

app/models/article.rb
class Article < ActiveRecord::Base
    #La tabla => articles
    #Campos => ActiveRecord, article.title()
    #Escribir métodos
    belongs_to :user
    has_many :comments
    validates :title, presence: true, uniqueness: true
    validates :body, presence: true , length: {minimum:20, maximum:1000}
    before_save :set_visits_count 

    def update_visits_count
        self.save if self.visits_count.nil?
        #Le decimos, el contador es nulo? pues llama a self.save(que esto va al hash before_save y llama a set visits count)
        self.update(visits_count: self.visits_count + 1)
    end
    private

    def set_visits_count
        self.visits_count ||= 0
        #or o igual, si el valor de visits count es nulo le asigna 0, sino es nulo no le asigna nada.
    end
end

app/models/category.rb
class Category < ActiveRecord::Base
    validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article 
  #associación de unos a muchos
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def set_categories
    @categories = Category.all
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    #GET /articles
    def index
        @articles = Article.all 
    end
    #GET /articles/:id
    def show
        @article = Article.find(params[:id])
        Article.where("id = ?", params[:id])
        @article.update_visits_count
        @comment = Comment.new
    end
    #GET /articles/new
    def new
        @article = Article.new
    end
    #POST /articles
    def create
        @article = current_user.articles.new(article_params)
        if @article.validate
            @article.save
            redirect_to @article
        else
            render :new
        end
    end
    def edit
        @article = Article.find(params[:id])
    end
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to @article
    end
    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article
        else
            render :edit
        end
    end

    private
    def article_params
        params.require(:article).permit(:title,:body,:categoria)
    end
    
    #Le decimos que los campos en los cuales el usuario puede actuar es el title y el body, básicamente para evitar posibles ataques.
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_article
  before_action :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:article_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @article = Article.all
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<h1><%= name %></h1>
<%= form_for(@article) do |f| %>
    <% @article.errors.full_messages.each do |message| %>
        <div class="be-red white top-space">
            * <%= message %>
        </div>
    <%end%>
    <div class="field">
        <%= f.text_field :title, placeholder:"Título", class:"form_control"%>
    </div>

    <div class="field">
        <%= f.text_area :body, placeholder:"Escribe aquí tu artículo", style:"height:250px;", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.submit "Guardar" ,class:"btn be-red white"%>
    </div>
<%end%>

app/views/articles/edit.html.erb
<div style="width:80%;margin:0 auto;">
    <%= render "partials/form", name:"Editar artículo" %>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
    <div class="articles">
        <h1><%= link_to article.title, article %></h1>
        <%= article.body %>
        <p><%= article.categoria%></p>
        <% if user_signed_in? %>
        <div class="field">
            <%= link_to "Eliminar", article, method: :delete, class:"red" %>
        </div>
        <%end%>
    </div>
</div>
<%end%>

app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
    <%= render "partials/form", name:"Crear artículo" %>
</div>

app/views/articles/show.html.erb
<%if @article.categoria == "Mamifero"%>
    <div class="MamiferoBackground">
    <%end%>
<%if @article.categoria == "Aves"%>
    <div class="AveBackground">
    <%end%>
<%if @article.categoria == "Anfibio"%>
    <div class="AnfibioBackground">
    <%end%>

<%if @article.categoria == "Reptil"%>
    <div class="ReptilBackground">
    <%end%>

    <div class="article col-md">
    <h1><%= @article.title %></h1>
    <%= @article.body %>
    <br>
    <% if not @article.user.nil? %> 
    Escrito por: <%= @article.user.email %>
    <p>En la categoria de: <%= @article.categoria%></p>
    <%end%>
    <p>Visitas: <%= @article.visits_count %> </p>
            <h3>Comentarios</h3>
                <% @article.comments.each do |comment| %>
                    <p>
                        <i><%= comment.body %></i>  - 
                        <%= comment.user.email %>
                    </p>
                <%end%>

            <%= render "comments/form" %>
     <% if user_signed_in? %>
    <%= link_to "Editar", edit_article_path(@article) ,class:"green" %>
    <%end%>
</div>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.color_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @category.color %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_form.html.erb
<%= form_for([@article,@comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :"Escribe tu comentario" %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ESPACIO SALVAJE</title>
  <link href="https://fonts.googleapis.com/stylesheets?family=Roboto" rel="stylesheet"> 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="jumbotron-fluid" style="padding:0px;">
    <header>
      <%= render "partials/navigation" %>
    </header>
    <p class="notice" style="display:none;"><%= notice %></p>
    <p class="alert" style="display:none;"><%= alert%></p>
  </div>
  <%= yield %>
</body>
</html>

app/views/partials/_form.html.erb
<h1><%= name %></h1>
<%= form_for(@article) do |f| %>
    <% @article.errors.full_messages.each do |message| %>
        <div class="be-red white top-space">
            * <%= message %>
        </div>
    <%end%>
    <div class="field">
        <%= f.text_field :title, placeholder:"Título", class:"form_control"%>
    </div>

    <div class="field">
        <%= f.text_area :body, placeholder:"Escribe aquí tu artículo", style:"height:250px;", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.select :categoria,([['Mamifero', 'Mamifero'], ['Reptil', 'Reptil'],['Anfibio','Anfibio'],['Aves','Aves']]) %>
    </div>
    <% if user_signed_in? %>
    <div class="field">
        <%= f.submit "Guardar" ,class:"btn btn-color white"%>
    </div>
    <%else%>
    <h4>NO puedes guardar el artículo ya que no has iniciado sesión</h4>
    <%end%>
<%end%>

app/views/partials/_navigation.html.erb
<nav> 
    <ul class="center-xs middle-xs nav nav-pills">  
    <h1 class="no-margin col-md" id="logo"> <%= link_to "ESPACIO SALVAJE", root_path %> </h1>
    <li class="col-md nav-item">
        <%= link_to "Artículos", articles_path %>
    </li>
    <li class="col-md nav-item">
        <%= link_to "Crear artículo", new_article_path %>
    </li>
    <% if user_signed_in? %>
        <h4>Bienvenido <%= current_user.email %></h4>
        <li class="col-md nav-item">
        <%= link_to "Cerrar sesión" , destroy_user_session_path , method: :delete %>
        </li>
    <%else%>
        <li class="col-md nav-item">
        <%= link_to "Iniciar sesión", new_user_session_path%>
        </li>
        <li class="col-md nav-item">
        <%= link_to "Crear cuenta", new_user_registration_path%>
        </li>
    <%end%>
    </ul>
</nav> 

app/views/welcome/index.html.erb
<div class="carousel-inner">
    <%= image_tag("background (1).jpg", :alt => "rss feed") %>
</div>


    